<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="3" failures="0" skipped="0" tests="3" time="2.480" timestamp="2025-09-24T03:52:24.659446+02:00" hostname="DESKTOP-7701MO7"><testcase classname="" name="unit_tests.test_data_loader" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\Lenovo\pontia\devops\entrega\pontia-mlops-tutorial-Guillermo-Prieto\unit_tests\test_data_loader.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\..\..\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test_data_loader.py:7: in &lt;module&gt;
    from data_loader import load_data, preprocess_data  # Update this import path as needed
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   ModuleNotFoundError: No module named 'data_loader'</error></testcase><testcase classname="" name="unit_tests.test_evaluate" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\Lenovo\pontia\devops\entrega\pontia-mlops-tutorial-Guillermo-Prieto\unit_tests\test_evaluate.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\..\..\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test_evaluate.py:4: in &lt;module&gt;
    from evaluate import evaluate
E   ModuleNotFoundError: No module named 'evaluate'</error></testcase><testcase classname="" name="unit_tests.test_model" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\Lenovo\pontia\devops\entrega\pontia-mlops-tutorial-Guillermo-Prieto\unit_tests\test_model.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\..\..\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test_model.py:3: in &lt;module&gt;
    from model import train_model
E   ModuleNotFoundError: No module named 'model'</error></testcase></testsuite></testsuites>